"""
Preset topology scenarios for common e2e test patterns.

Functions that return pre-configured TopologyBuilder instances, reducing
boilerplate in test files. Each scenario represents a common network
topology used in testing.

Common scenarios:
  - single_satellite(): T1 — 1 master, 1 satellite
  - three_satellites(): T2 — 1 master, 3 satellites
  - with_relay(): T9 — 1 master, relay, satellites under relay
  - chain_topology(): T3 — Master → Relay → Satellites
  - star_topology(): Radial topology with one central master
  - with_acl_enforcement(): Topology with ACL rules pre-configured

Usage:

  from hivescope.scenarios import single_satellite

  def test_something():
      b = single_satellite()
      m = b.get_master("M0")
      s = b.get_satellite("S0")
      b.start_all()
      # ... assertions ...
      b.stop_all()
"""

from typing import Optional, Dict, Any, List

from hivescope.topology import TopologyBuilder
from hivescope.plugins.agent import TestAgentProtocol


def single_satellite(allowed_types: Optional[List[str]] = None) -> TopologyBuilder:
    """
    Simple T1 topology: 1 master, 1 satellite.

    The satellite is registered with its own identity key and password, which
    are generated by ``make_identity`` inside ``SatelliteNode.create()``.
    Pass ``allowed_types`` to grant the satellite permission to inject those
    OVOS bus message types (empty / None denies all by default — whitelist model).

    Perfect for testing basic handshake, encryption, message routing.
    """
    b = TopologyBuilder()
    m = b.add_master("M0")
    # allowed_types flows through connect_kwargs → SatelliteNode.connect() →
    # register_satellite(key=satellite.identity.access_key, ...) so the DB
    # entry for the satellite's own UUID key carries the correct whitelist.
    b.add_satellite("S0", upstream=m, allowed_types=allowed_types)
    return b


def admin_satellite(allowed_types: Optional[List[str]] = None) -> TopologyBuilder:
    """
    T1 with the satellite granted ``is_admin=True``.

    Admin status lets the satellite use the reserved ``session_id="default"``
    (normally rejected from non-admin peers); it does NOT bypass the OVOS
    bus message-type allowlist. Pass ``allowed_types=[...]`` to grant the
    message types the satellite needs to inject.
    """
    b = TopologyBuilder()
    m = b.add_master("M0")
    # is_admin and allowed_types flow through connect_kwargs → SatelliteNode.connect()
    # → register_satellite(key=satellite.identity.access_key, ...) so the DB
    # entry for the satellite's own UUID key carries both flags.
    b.add_satellite("S0", upstream=m, is_admin=True, allowed_types=allowed_types)
    return b


def three_satellites() -> TopologyBuilder:
    """
    T2 topology: 1 master, 3 satellites.

    Satellites S0, S1, S2, each with its own generated credentials.

    Perfect for testing broadcast, propagate, peer-to-peer routing.
    """
    b = TopologyBuilder()
    m = b.add_master("M0")

    # Each satellite registers itself under its own generated access key when
    # it connects; no pre-registration with fixed keys is needed.
    for i in range(3):
        b.add_satellite(f"S{i}", upstream=m)

    return b


def with_relay() -> TopologyBuilder:
    """
    T9 topology: 1 master, 1 relay, 2 satellites under relay.

    Tests message routing through a dual-role relay node.

    Topology:
      M0
      └── R0 (relay: master facing upstream, satellite facing downstream)
          ├── S0
          └── S1
    """
    b = TopologyBuilder()
    m = b.add_master("M0")

    r = b.add_relay("R0", upstream=m)

    # Satellites under the relay: credentials are generated per-satellite by
    # SatelliteNode.connect(), so no pre-registration is needed here.
    b.add_satellite("S0", upstream=r)
    b.add_satellite("S1", upstream=r)

    return b


def chain_topology() -> TopologyBuilder:
    """
    T3 topology: M0 → R0 → S0 (chain of 3 nodes).

    Tests multi-hop escalate, propagate, and message routing.

    Topology:
      M0
      └── R0 (relay)
          └── S0
    """
    b = TopologyBuilder()
    m = b.add_master("M0")
    r = b.add_relay("R0", upstream=m)

    b.add_satellite("S0", upstream=r)

    return b


def star_topology(num_satellites: int = 5) -> TopologyBuilder:
    """
    Star topology: 1 central master, N satellites all connected directly.

    Tests broadcast/propagate to many peers simultaneously.

    Args:
      num_satellites: Number of satellites (default 5)
    """
    b = TopologyBuilder()
    m = b.add_master("M0")

    for i in range(num_satellites):
        b.add_satellite(f"S{i}", upstream=m)

    return b


def with_acl_enforcement() -> TopologyBuilder:
    """
    Topology pre-configured for policy-admission ACL testing.

    Three satellites covering the two policy-layer enforcement paths:

    - **S_ADMIN** — admin satellite granted a broad ``allowed_types``
      whitelist (``recognizer_loop:utterance`` + ``speak``).  Represents a
      fully-trusted peer.
    - **S_RESTRICTED_TYPE** — non-admin satellite whose ``allowed_types``
      excludes ``recognizer_loop:utterance``.  Any utterance it injects is
      denied by ``MessageTypeACLPolicy`` with code
      ``ACL_DISALLOWED_TYPE`` and never reaches the agent bus.
    - **S_RESTRICTED_SKILL** — non-admin satellite allowed to inject
      ``recognizer_loop:utterance`` but registered with
      ``skill_blacklist=["skill-weather"]``.  Its utterances pass the type
      gate and reach the agent bus, but ``OVOSAgentPolicy`` injects
      ``session.blacklisted_skills = ["skill-weather"]`` via an
      ``AddBlacklistedSkill`` mutation so the OVOS pipeline cannot route
      them to the blacklisted skill.

    Admission control flows through the ``PolicyChain``
    (``MessageTypeACLPolicy`` force-prepended, then ``OVOSAgentPolicy``
    for the skill/intent injection).
    """
    b = TopologyBuilder()
    m = b.add_master("M0")

    # Admin satellite — full utterance + speak access
    b.add_satellite(
        "S_ADMIN",
        upstream=m,
        is_admin=True,
        can_propagate=True,
        can_escalate=True,
        allowed_types=["recognizer_loop:utterance", "speak"],
    )

    # Type-restricted satellite — speak only, utterance is DENIED
    b.add_satellite(
        "S_RESTRICTED_TYPE",
        upstream=m,
        is_admin=False,
        allowed_types=["speak"],          # excludes recognizer_loop:utterance
    )

    # Skill-blacklisted satellite — utterance allowed, but OVOSAgentPolicy
    # injects session.blacklisted_skills=["skill-weather"] on each message
    b.add_satellite(
        "S_RESTRICTED_SKILL",
        upstream=m,
        is_admin=False,
        allowed_types=["recognizer_loop:utterance"],
        skill_blacklist=["skill-weather"],
    )

    return b


def hierarchical_hubs(num_levels: int = 3, sats_per_relay: int = 2) -> TopologyBuilder:
    """
    Hierarchical topology: nested masters/relays for testing deep routing.

    Args:
      num_levels: Depth of hierarchy (2 = M0→R0, 3 = M0→R0→R1, etc.)
      sats_per_relay: Satellites per relay node
    """
    b = TopologyBuilder()
    m = b.add_master("M0")

    # Build relay chain
    prev_node = m
    relays = []
    for level in range(1, num_levels):
        r = b.add_relay(f"R{level}", upstream=prev_node)
        relays.append(r)
        prev_node = r

    # Add satellites at the last level
    for i in range(sats_per_relay):
        b.add_satellite(f"S{i}", upstream=prev_node)

    return b


def with_multiple_agent_protocols(agent_protocol: Optional[TestAgentProtocol] = None) -> TopologyBuilder:
    """
    Topology where master uses a custom agent protocol.

    Useful for testing agent protocol implementations.

    (Default: TestAgentProtocol; can be overridden by caller via ``agent_protocol``)
    """
    b = TopologyBuilder()
    m = b.add_master("M0", agent_protocol=agent_protocol)
    b.add_satellite("S0", upstream=m)
    return b
